### ISSUE TITLE
Error when installing Moonraker

### ISSUE THREAD

**Issue by sisyphusSmiling** [d4rk50ul1/klipper-on-android#35]
Following the instructions as presented, I'm met with an error I can't seem to get past when installing Moonraker. While in the step creating the virtual environment, I get the following

```bash
Thanks buddy! Here's the error:

Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [189 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-37
      creating build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/_version.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/_binary.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/features.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/__init__.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/QoiImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/_util.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/Image.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/_deprecate.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/__main__.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-cpython-37/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-cpython-37/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "/tmp/pip-install-td8leqae/pillow_1bc6a34b935246d0816f1495c788760c/setup.py", line 997, in <module>
          zip_safe=not (debug_build() or PLATFORM_MINGW),
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/android/moonraker-env/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
          super().run_command(command)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 84, in run
          _build_ext.run(self)
        File "/home/android/moonraker-env/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
          self.build_extensions()
        File "/tmp/pip-install-td8leqae/pillow_1bc6a34b935246d0816f1495c788760c/setup.py", line 809, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-td8leqae/pillow_1bc6a34b935246d0816f1495c788760c/setup.py", line 1010, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
```

I confirmed that zlib is installed, and installed pillow directly from the home directory. Not sure where to go from here.

**Comment by MrAngryStump** [comment]
i have absolutely same issue

**Comment by Pescu123** [comment]
You could try to follow [this](https://github.com/python-pillow/Pillow/issues/4242) thread to troubleshoot your problem. You can see in the log that you send that the problem is this: 

> The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

**Comment by AdamMhm** [comment]
I had the same problem, but problem was gone when i switched config of linux deploy to debian oldstable (was using arm64)

**Comment by wischm0b** [comment]
> I had the same problem, but problem was gone when i switched config of linux deploy to debian oldstable (was using arm64)

That worked for me.
